apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infras/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: muhammad0320/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
