apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  googleCloudBuild:
    projectId: innate-algebra-414708

  artifacts:
    - image: us.gcr.io/innate-algebra-414708/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
